-- =====================================================
-- OpsPilot AI: RAW Tables
-- These tables store original CSV data with minimal changes
-- =====================================================

USE DATABASE OPSPILOT_AI;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_CANDY_SALES (
    ROW_ID INTEGER,
    ORDER_ID STRING,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    SHIP_MODE STRING,
    CUSTOMER_ID INTEGER,
    COUNTRY_REGION STRING,
    CITY STRING,
    STATE_PROVINCE STRING,
    POSTAL_CODE STRING,
    DIVISION STRING,
    REGION STRING,
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    SALES FLOAT,
    UNITS INTEGER,
    GROSS_PROFIT FLOAT,
    COST FLOAT
);

CREATE OR REPLACE TABLE RAW_CANDY_PRODUCTS (
    DIVISION STRING,
    PRODUCT_NAME STRING,
    FACTORY STRING,
    PRODUCT_ID STRING,
    UNIT_PRICE FLOAT,
    UNIT_COST FLOAT
);

CREATE OR REPLACE TABLE RAW_CANDY_FACTORIES (
    FACTORY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);

CREATE OR REPLACE TABLE RAW_CANDY_TARGETS (
    DIVISION STRING,
    TARGET FLOAT
);