-- =====================================================
-- OpsPilot AI: STAGING Tables
-- Cleaned and standardized data from RAW layer
-- =====================================================

USE DATABASE OPSPILOT_AI;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STG_CANDY_SALES (
    ROW_ID INTEGER,
    ORDER_ID STRING,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    CORRECTED_SHIP_DATE DATE,
    SHIP_MODE STRING,
    CUSTOMER_ID INTEGER,
    COUNTRY_REGION STRING,
    CITY STRING,
    STATE_PROVINCE STRING,
    POSTAL_CODE STRING,
    DIVISION STRING,
    REGION STRING,
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    SALES FLOAT,
    UNITS INTEGER,
    GROSS_PROFIT FLOAT,
    COST FLOAT,
    SHIPPING_DAYS INTEGER,
    PROFIT_MARGIN FLOAT
);

CREATE OR REPLACE TABLE STG_CANDY_PRODUCTS (
    DIVISION STRING,
    PRODUCT_NAME STRING,
    FACTORY STRING,
    PRODUCT_ID STRING,
    UNIT_PRICE FLOAT,
    UNIT_COST FLOAT
);

CREATE OR REPLACE TABLE STG_CANDY_FACTORIES (
    FACTORY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);

CREATE OR REPLACE TABLE STG_CANDY_TARGETS (
    DIVISION STRING,
    TARGET FLOAT
);