-- =====================================================
-- OpsPilot AI: MARTS Tables
-- Business-ready analytics tables
-- =====================================================

USE DATABASE OPSPILOT_AI;
USE SCHEMA MARTS;

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY INTEGER AUTOINCREMENT,
    ROW_ID INTEGER,
    ORDER_ID STRING,
    ORDER_DATE DATE,
    CORRECTED_SHIP_DATE DATE,
    SHIP_MODE STRING,
    CUSTOMER_ID INTEGER,
    PRODUCT_ID STRING,
    LOCATION_KEY STRING,
    DIVISION STRING,
    REGION STRING,
    SALES FLOAT,
    UNITS INTEGER,
    GROSS_PROFIT FLOAT,
    COST FLOAT,
    SHIPPING_DAYS INTEGER,
    PROFIT_MARGIN FLOAT
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    DIVISION STRING,
    FACTORY STRING,
    UNIT_PRICE FLOAT,
    UNIT_COST FLOAT
);

CREATE OR REPLACE TABLE DIM_FACTORY (
    FACTORY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);

CREATE OR REPLACE TABLE DIM_LOCATION (
    LOCATION_KEY STRING,
    COUNTRY_REGION STRING,
    CITY STRING,
    STATE_PROVINCE STRING,
    POSTAL_CODE STRING,
    REGION STRING
);

CREATE OR REPLACE TABLE DIM_TARGET (
    DIVISION STRING,
    TARGET FLOAT
);